#!/usr/bin/env bash
# Publish the portal to the Azure Static Web App, pointed at Azure.
#
#     bash azure/deploy-frontend.sh
#
# Run from the repo root in Cloud Shell.
#
# IT NEVER TOUCHES THE REPO. config.js in git still points at Supabase, because
# GitHub Pages serves that file to real users. This builds a staging copy,
# writes an Azure config INTO THE COPY, and deploys that. Nothing tracked
# changes, so there is no way to accidentally push an Azure config to the live
# site.
set -uo pipefail

RG="${RG:-rg-cxportal-dev}"
SWA="${SWA:-stapp-cxportal-dev}"
TENANT="${TENANT:-e62c5154-d15d-4c22-a489-aa656aff64a4}"
APPID="${APPID:-a1301867-e12c-43c7-85e2-80cc5bd9d325}"
STAGE="${STAGE:-$HOME/cx-portal-azure-staging}"

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }

[ -f index.html ] || { echo "run this from the repo root"; exit 1; }

say "1/5  discovering endpoints"
API="$(az containerapp show -g "$RG" -n ca-postgrest-dev \
  --query properties.configuration.ingress.fqdn -o tsv)" || exit 1
HOST="$(az staticwebapp show -g "$RG" -n "$SWA" --query defaultHostname -o tsv)" || exit 1
echo "  API : https://$API"
echo "  site: https://$HOST"

say "2/5  staging a copy (the repo is not modified)"
rm -rf "$STAGE"; mkdir -p "$STAGE"
tar -c --exclude=.git --exclude=node_modules --exclude=azure --exclude=infra \
       --exclude=tools --exclude=supabase --exclude='*.md' . | tar -x -C "$STAGE"
echo "  staged $(find "$STAGE" -type f | wc -l) files in $STAGE"

say "3/5  writing the Azure config into the staging copy"
cat > "$STAGE/config.js" <<CFG
// GENERATED by azure/deploy-frontend.sh — do not edit, and do not copy this
// back into the repo. The tracked config.js points at Supabase because that is
// what GitHub Pages serves to real users.
window.CX_CONFIG = {
  IDENTITY: 'entra',
  ENTRA_TENANT_ID: '$TENANT',
  ENTRA_CLIENT_ID: '$APPID',
  ENTRA_API_SCOPE: 'api://$APPID/access_as_user',
  ENTRA_REDIRECT_URI: 'https://$HOST/',

  // The PostgREST gateway. The app speaks plain PostgREST, so the variable
  // keeps its old name — only the value moved.
  SUPABASE_URL: 'https://$API',
  SUPABASE_ANON_KEY: '',

  // Supabase mounts PostgREST under /rest/v1/; a self-hosted one serves at the
  // root. Without this every table 404s while authentication works perfectly,
  // which looks like a missing database and is a URL prefix.
  REST_PATH: '',
};
CFG
echo "  wrote $STAGE/config.js"

say "4/5  widening the CSP for the Azure endpoints"
# The policy names the Supabase origin. Add the PostgREST host, or every API
# call is blocked by the browser before it leaves the page — and the console
# says "Refused to connect", which is easy to misread as the API being down.
python3 - "$STAGE/index.html" "https://$API" <<'PY'
import re, sys
path, api = sys.argv[1], sys.argv[2]
raw = open(path, 'rb').read()
crlf = b'\r\n' in raw
s = raw.decode('utf8')
if crlf: s = s.replace('\r\n', '\n')
m = re.search(r'(<meta http-equiv="Content-Security-Policy" content=")([^"]+)(")', s)
if not m:
    print('  no CSP meta tag found'); sys.exit(0)
csp = m.group(2)
if api not in csp:
    csp = csp.replace('connect-src ', 'connect-src ' + api + ' ')
    s = s[:m.start(2)] + csp + s[m.end(2):]
    if crlf: s = s.replace('\n', '\r\n')
    open(path, 'wb').write(s.encode('utf8'))
    print('  added ' + api + ' to connect-src')
else:
    print('  already present')
PY

say "5/5  deploying"
TOKEN="$(az staticwebapp secrets list -g "$RG" -n "$SWA" \
  --query properties.apiKey -o tsv)" || exit 1
npx -y @azure/static-web-apps-cli deploy "$STAGE" \
  --deployment-token "$TOKEN" --env production --no-use-keychain 2>&1 | tail -20

cat <<DONE

  Open:  https://$HOST

  Sign in with your Azure account. What to watch in the browser console:
    [identity] entra ready — signed in as ...
  and then whether module lists have rows.

  Empty lists after a successful sign-in mean the token reached PostgREST but
  the session did not become 'authenticated', or private.mfa_ok() denied.
  Check the token at https://jwt.ms — it must contain:
    "roles": ["authenticated"]      <- makes PostgREST switch database role
    "oid":   "<your object id>"     <- what auth.uid() resolves
DONE
