#!/usr/bin/env bash
# Publish the portal to the Azure Static Web App, pointed at Azure.
#
#     bash azure/deploy-frontend.sh
#
# Run from the repo root in Cloud Shell.
#
# IT NEVER TOUCHES THE REPO. config.js in git still points at Supabase, because
# GitHub Pages serves that file to real users. This writes an Azure config to a
# scratch folder, builds the site with it (tools/build.js), and deploys that.
# Nothing tracked changes, so there is no way to accidentally push an Azure
# config to the live site.
set -uo pipefail

RG="${RG:-rg-cxportal-dev}"
SWA="${SWA:-stapp-cxportal-dev}"
TENANT="${TENANT:-e62c5154-d15d-4c22-a489-aa656aff64a4}"
APPID="${APPID:-a1301867-e12c-43c7-85e2-80cc5bd9d325}"
STAGE="${STAGE:-$HOME/cx-portal-azure-staging}"
# Object id of the CX Portal Users group. Set it (entra only) and Directory →
# Add Person / Inactive / Remove manage that group in Microsoft directly.
USERS_GROUP="${USERS_GROUP:-}"

# WHICH SIGN-IN SCREEN THIS BUILD GETS.
#   postgrest : email + password, exactly as on Supabase. Needs
#               supabase/sql/azure_local_auth.sql applied and PGRST_JWT_SECRET
#               set to the same secret (azure/configure-postgrest.sh --local).
#   entra     : redirect to Microsoft. Needs the app registration and
#               PGRST_JWT_SECRET set to Entra's JWKS.
# Both are supported end to end; this is the only line that chooses.
IDENTITY="${IDENTITY:-postgrest}"

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }

[ -f index.html ] || { echo "run this from the repo root"; exit 1; }

say "1/5  discovering endpoints"
API="$(az containerapp show -g "$RG" -n ca-postgrest-dev \
  --query properties.configuration.ingress.fqdn -o tsv)" || exit 1
HOST="$(az staticwebapp show -g "$RG" -n "$SWA" --query defaultHostname -o tsv)" || exit 1
echo "  API : https://$API"
echo "  site: https://$HOST"

say "2/5  preparing a scratch folder (the repo is not modified)"
rm -rf "$STAGE"; mkdir -p "$STAGE"

say "3/5  writing the Azure config"
# THIS FILE IS REPLACED WHOLESALE, WHICH IS WHY config.js MUST HOLD ONLY VALUES.
# window.REST_BASE used to be defined in the tracked config.js. This heredoc does
# not reproduce it, so on Azure it did not exist — app.js reads REST_BASE as a
# bare global, every data call threw ReferenceError before building a URL, and
# _checkDbStatus() painted "SYSTEM OFFLINE" over a completely healthy API.
# Derivation now lives in cx-config.js, which this script does not touch.
# tools/test_config_seam.js runs THIS heredoc and fails if the split breaks again.
{
cat <<CFG
// GENERATED by azure/deploy-frontend.sh — do not edit, and do not copy this
// back into the repo. The tracked config.js points at Supabase because that is
// what GitHub Pages serves to real users.
//
// VALUES ONLY. Anything derived from these belongs in cx-config.js — this file
// is overwritten per environment, so logic placed here disappears silently.
window.CX_CONFIG = {
  IDENTITY: '$IDENTITY',
CFG
if [ "$IDENTITY" = "entra" ]; then
cat <<CFG
  ENTRA_TENANT_ID: '$TENANT',
  ENTRA_CLIENT_ID: '$APPID',
  ENTRA_API_SCOPE: 'api://$APPID/access_as_user',
  ENTRA_REDIRECT_URI: 'https://$HOST/',
CFG
if [ -n "${USERS_GROUP:-}" ]; then echo "  ENTRA_USERS_GROUP_ID: '${USERS_GROUP}',"; fi
fi
cat <<CFG

  // The PostgREST gateway. No anon key: that is a Supabase-only header.
  API_URL: 'https://$API',

  // Supabase mounts PostgREST under /rest/v1/; a self-hosted one serves at the
  // root. Without this every table 404s while authentication works perfectly,
  // which looks like a missing database and is a URL prefix. cx-config.js turns
  // this into window.REST_BASE.
  REST_PATH: '',
};
CFG
} > "$STAGE/config.js"
echo "  wrote $STAGE/config.js  (identity: $IDENTITY)"

say "4/5  building the site for this environment"
# tools/build.js copies only what the browser needs into $STAGE/site, swaps in
# the config.js written above, points the CSP at the hosts that config names
# (a policy naming only Supabase blocks every Azure call with "Refused to
# connect", easily misread as the API being down), and stamps the service
# worker's cache version so clients actually pick up the new build.
node tools/build.js --config "$STAGE/config.js" --out "$STAGE/site" || exit 1

say "5/5  deploying"
TOKEN="$(az staticwebapp secrets list -g "$RG" -n "$SWA" \
  --query properties.apiKey -o tsv)" || exit 1
npx -y @azure/static-web-apps-cli deploy "$STAGE/site" \
  --deployment-token "$TOKEN" --env production --no-use-keychain 2>&1 | tail -20

cat <<DONE

  Open:  https://$HOST

  Identity: $IDENTITY
    postgrest -> the normal email + password card. If it rejects a correct
                 password, the secret in private.auth_secrets and
                 PGRST_JWT_SECRET have drifted apart; re-run
                 azure/configure-postgrest.sh --local.
    entra     -> a 'Sign in with Microsoft' button. Watch for
                 [identity] entra ready — signed in as ...

  Empty lists after a successful sign-in mean the token reached PostgREST but
  the session did not become 'authenticated', or private.mfa_ok() denied.
  Check the token at https://jwt.ms — it must contain:
    "roles": ["authenticated"]      <- makes PostgREST switch database role
    "oid":   "<your object id>"     <- what auth.uid() resolves
DONE
